//echo Testing GET /api/geotags
GET http://localhost:3000/api/geotags
###

GET http://localhost:3000/api/geotags?searchTerm=edu
###
GET http://localhost:3000/api/geotags?searchTerm=edu&latitude=49.0163498971946&longitude=8.390911128469323

###
//echo Testing GET /api/geotags/:id
GET http://localhost:3000/api/geotags/1 HTTP/1.1
###
GET http://localhost:3000/api/geotags/12 HTTP/1.1

###
//echo Testing POST /api/geotags
POST http://localhost:3000/api/geotags -d @invalid.json
###
POST http://localhost:3000/api/geotags -d @valid.json

###
//echo Testing PUT /api/geotags
PUT http://localhost:3000/api/geotags/1 -d @invalid.json
###
PUT http://localhost:3000/api/geotags/1 -d @valid.json

###
//echo Testing DELETE /api/geotags/:id
DELETE http://localhost:3000/api/geotags/1
###
DELETE http://localhost:3000/api/geotags/12 HTTP/1.1