
###
POST http://localhost:3000/api/geotags
Content-Type: application/json

{
  "lat": "87.204",
  "long": "56.209",
  "name": "HalloWorld",
  "hashtag": "#Man"
}


###
GET http://localhost:3000/api/geotags

###
POST http://localhost:3000/api/geotags
Content-Type: application/json

{
  "lat": "67.204",
  "long": "75.209",
  "name": "Foo",
  "hashtag": "#Foo"
}

###
GET http://localhost:3000/api/geotags?latitudeDiscovery="67.204"&longitudeDiscovery="75.209"


###
GET http://localhost:3000/api/geotags/1



