POST http://localhost:3000/geotags
Content-Type: application/json

{
  "latitude": 1,
  "longitude": 2,
  "name": "echo1",
  "hashtag": "#asfe"
}

###

GET http://localhost:3000/geotags

###

GET http://localhost:3000/geotags/0

###

GET http://localhost:3000/geotags/4

###

GET http://localhost:3000/geotags?discovery=HSKA

###

DELETE http://localhost:3000/geotags/0

###