POST http://localhost:3000/tagging
Content-Type: application/json

{
  "newTagList": [
    {
      "latitude": 1,
      "longitude": 2,
      "name": "echo",
      "hashtag": "#asfe"
    }
  ],
  "latitude":1,
  "longitude":2
}

###

POST http://localhost:3000/tagging

###

GET http://localhost:3000/discovery
Content-Type: application/json

{
  "searchTerm":"#dd",
  "latitude":49.1243,
  "longitude":8.598
}

###